### ISSUE TITLE
Make `ArkState` immutable

### ISSUE THREAD

**Issue by apt1002** [ursalang/ark#1]
`FexprClosure.call()` does this:
```
      ark.stack = ark.stack.pushFrame([frame, this.freeVars])
      res = this.children[0].eval(ark)
      ark.stack = oldStack
```

This won't work if the body of the function saves a continuation.

**Comment by rrthomas** [comment]
Also should make the debug stacks immutable.

**Comment by rrthomas** [comment]
I have fixed these two issues. More work to do to support continuations, though.
