### ISSUE TITLE
Sort out captures at compile time

### ISSUE THREAD

**Issue by apt1002** [ursalang/ark#2]
Currently, we compile all symbol references as stack references (`StackRef`), and then later turn some of them into capture references (`CaptureRef`).

Instead, do it all at symbol resolution time (`symRef()`).

**Comment by apt1002** [comment]
(This will get rid of all the `parentRef` nonsense.)

**Comment by rrthomas** [comment]
In order to do this, need to accumulate function captures while compiling (rather than computing them in `Fexpr`'s constructor).
