### ISSUE TITLE
`FreeVarsMap` should only contain `StackRef`s

### ISSUE THREAD

**Issue by apt1002** [ursalang/ark#3]

**Comment by rrthomas** [comment]
Actually, it can contain `ValRef`s too; nonetheless, make the type more precise.

**Comment by apt1002** [comment]
I think ValRefs are constants, not captures. In particular there's nothing to do when the closure is constructed.

**Comment by rrthomas** [comment]
`ValRef`s aren't constants, they're heap locations.

**Comment by rrthomas** [comment]
We did get there: `FreeVarsMap` now only contains `ArkStackRef`.
